clear;clc
datafile='D:\CaSCN\GM_PT';%所有灰质文件(.nii)所在的文件夹路径
%brainmaskfile指定全脑灰质mask，可以选择vbm统计结果文件夹下的mask.nii
brainmaskfile='D:\CaSCN\stats\mask.nii';
%seedmask指定种子点mask
seedmask='D:\CaSCN\stats\thalamus.nii';
%savedir结果保存路径
savedir='D:\CaSCN\voxel_wise_GCA';
%scores指定时间相关指标，如病程、认知量表等，一列，行数和.nii数目相同
scores='D:\CaSCN\cognition.txt';
order=1;%格兰杰因果的阶数，不需要修改
method='ascend';%被试根据量表升序排列还是降序排列，%'ascend'和'descend'
covs=[];%协变量，如年龄、性别、TIV等，放在一个txt里，行是被试，列是协变量，没有就置空[]
flag_regscore=1;%是否回归协变量，1，是，0，否，如果是，自动回归协变量以及量表分的间隔
thresh=0.5;%显著性水平，推荐0.05
corrmethod='none';%多重比较校正，'none','FDR',实际用FDR
%% 以下不用改
flag='Z';
outputdir=savedir;
maskfile=brainmaskfile;
JQ_gca_voxelwise(seedmask,datafile,savedir,order,covs,brainmaskfile,scores,method,flag_regscore)
statmapfile=fullfile(savedir,'zgc_maptoseed01.nii');
[sthr1,pthr1]=JQ_thresh_statmap_fdr(statmapfile,maskfile,thresh,flag,corrmethod,[],[],outputdir);
[~,name,~]=fileparts(statmapfile);
thrdmap=fullfile(outputdir,[name,'_',corrmethod,strrep(num2str(thresh),'.',''),'.nii']);
JQ_img2ary(thrdmap);
statmapfile=fullfile(savedir,'zgc_seed01tomap.nii');
[sthr2,pthr2]=JQ_thresh_statmap_fdr(statmapfile,maskfile,thresh,flag,corrmethod,[],[],outputdir);
[~,name,~]=fileparts(statmapfile);
thrdmap=fullfile(outputdir,[name,'_',corrmethod,strrep(num2str(thresh),'.',''),'.nii']);
JQ_img2ary(thrdmap);
